### ISSUE TITLE
Installation failed using composer

### ISSUE THREAD

**Issue by maheshtc** [tugmaks/yii2-rss-reader#1]
I tried to install 2 3 times for installing this extension, But It is failed. 

Your requirements could not be resolved to an installable set of packages.  

Problem 1
    - The requested package tugmaks/yii2-rss-reader could not be found in any version, there may be a typo in the package name.

Please help me to resolve the above issue

**Comment by tugmaks** [comment]
@maheshtc just use "tugmaks/yii2-rss-reader": "dev-master"

I will fix it later

**Comment by tugmaks** [comment]
also mistake in usage example. Should be

``` php
<?php
echo \tugmaks\RssFeed\RssReader::widget([
    'channel' => 'http://yiifeed.com/news/rss',
    'pageSize' => 5,
    'itemView' => 'item', //To set own viewFile set 'itemView'=>'@frontend/views/site/_rss_item'. Use $model var to access item properties
    'wrapTag' => 'div',
    'wrapClass' => 'rss-wrap',
]);
?>
```

**Comment by maheshtc** [comment]
Thanks It is working now.

**Comment by noname007** [comment]
λ composer require --prefer-dist tugmaks/yii2-rss-reader "*"
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tugmaks/yii2-rss-reader * is satisfiable by tugmaks/yii2-rss-reader[dev-master] but these conflict with your requirements or minimum-stability.
